### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by aliazani**
I removed a print(type(date)) ==> line 453

Change sheet name ==> 402 sheet INVALIDS --> you copied from the upper one so you forget to change it.

### CODE REVIEW

**Comment by mhkarimi1383** [comment]
yeah, your right always @jadijadi says that Don't copy it's bad and he does a copy and then we have some problems like that.

**Comment by aliazani** [comment]
I'm not expert, and so I'am not sure about changes 
I made a mistake last time with id but that seems ok but I ask jadi to check it.

**Comment by mhkarimi1383** [comment]
@jadijadi

**Comment by jadijadi** [comment]
بسیار هم ممنون و هر دو درست است ولی چون کد رو خیلی تغییر دادم الان این رو مرج نمی کنم. ببخشید تقصیر من بود که دیر چک کردم

**Pull request closed without merging**
